server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: shortener_service_route
          uri: lb://shortener-service
          predicates:
            - Path=/api/shorten

        - id: redirection_service_route
          uri: lb://redirection-service
          predicates:
            - Path=/url/{alias}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

message: "Configuration for API Gateway from Config Server!"